name: FTP Test

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.freshboiler.co.uk
          username: ftpfreshboiler@freshboiler.co.uk
          password: ${{ secrets.ftp_password }}
